export const metaInfo = {
  en: {
    "Home.title": "Home",
    "Home.description":
      "Welcome to the home pageThe National Data and Analytics Platform (NDAP) facilitates and improves access to Indian government data. Through the platform, data sets from across India's extensive administrative landscape can be accessed. NDAP allows users to search, merge, visualize, and download datasets easily.",
  },
  te: {
    "Home.title": " నేషనల్ డేటా & ఎనలిటిక్స్",
    "Home.description":
      "నేషనల్ డేటా అండ్ అనలిటిక్స్ ప్లాట్‌ఫారమ్ (NDAP) అనేది అన్ని డేటా-సంబంధిత అవసరాలకు ఒక-స్టాప్ సొల్యూషన్. ఇది వివిధ మంత్రిత్వ శాఖలు మరియు విభాగాల నుండి విస్తృత శ్రేణి డేటాసెట్‌లకు ప్రాప్యతను అందిస్తుంది, వినియోగదారులు డేటాను సులభంగా శోధించడానికి, విలీనం చేయడానికి, దృశ్యమానం చేయడానికి మరియు డౌన్‌లోడ్ చేయడానికి అనుమతిస్తుంది. ప్లాట్‌ఫారమ్ డేటా స్టాండర్డైజేషన్, డేటా మెర్జింగ్ మరియు డేటా విజువలైజేషన్ వంటి అనేక రకాల ఫీచర్‌లను కూడా అందిస్తుంది, ఇది పరిశోధకులు, విధాన రూపకర్తలు మరియు సాధారణ ప్రజలకు విలువైన వనరుగా చేస్తుంది.",
  },
  hi: {
    "Home.title": "होम",
    "Home.description":
      "राष्ट्रीय डेटा और एनालिटिक्स प्लेटफॉर्म (एनडीएपी) भारतीय सरकारी डेटा तक पहुंच को सुविधाजनक बनाता है और सुधारता है। प्लेटफॉर्म के माध्यम से, भारत के व्यापक प्रशासनिक भूमि से डेटासेट तक पहुंचा जा सकता है। एनडीएपी उपयोगकर्ताओं को डेटासेट को आसानी से खोजने, मर्ज करने, दृश्यीकरण करने और डाउनलोड करने की सुविधा प्रदान करता है।",
  },
};

const basicData = {
  name: "National Data and Analytics Platform",
  description:
    "The National Data and Analytics Platform (NDAP) facilitates and improves access to Indian government data. Through the platform, data sets from across India's extensive administrative landscape can be accessed. NDAP allows users to search, merge, visualize, and download datasets easily.",
  keywords: [
    "Aam Aadmi Bima Yojana",
    "AgMarkNet,Commodity Wise Price and Arrival Data",
    "Agricultural Census ",
    "Annavitran - Distribution of Food Grains",
    "Annual Survey of Industries (ASI)",
    "Atal Pension Yojana",
    "AYUSH Infrastructure and Facilities",
    "Basic Statistical Returns of Scheduled Commercial Banks in India",
    "Census 2011",
    "Central Electricity Authority (CEA) Monthly Power Reports",
    "Climate Vulnerability Assessment for Adaptation Planning in India",
    "Coal Directory",
    "Common Service Centre (CSC) Roll-out Status",
    "Comprehensive National Nutrition Survey (CNNS)",
    "Crime in India",
    "Data on Chemical Fertilizers",
    "DBIE-Database on Indian Economy",
    "Department of Administrative Reforms and Public Grievances",
    "Digital India Dashboard",
    "Direct Benefit Transfer Data (DBT)",
    "Direct Benefit Transfer In Agriculture Mechanization",
    "e-Anudaan",
    "Early Childhood Care and Education (ECCE)",
    "Economic Census",
    "Economic Census - 2013",
    "Energy Dashboard",
    "Financial Assistance Provided by NFDB (National Fisheries Development Board)",
    "Foreign Direct Investment Statistics",
    "Fourth All India Handloom Census",
    "Goods and Services Tax (GST) Statistics",
    "Handbook of Statistics on Indian Economy  ",
    "Handbook of Statistics on Indian States",
    "Health Management Information System ",
    "Health Management Information System (HMIS)",
    "Indian Public Finance Statistics ",
    "Indian Railways Yearbook",
    "Input Survey 2016-17",
    "Integrated Skill Development Scheme (ISDS)",
    "Issuing Passports",
    "Land Use Statistics",
    "Livestock Census",
    "Mahatma Gandhi National Rural Employment Guarantee Act",
    "Mahatma Gandhi National Rural Employment Guarantee Act (MGNREGA) ",
    "Marine Fisheries Census",
    "Micro Small and Medium Enterprise Dashboard",
    "Minerals Statistics",
    "Monthly Power Reports",
    "National Achievement Survey (NAS)",
    "National Family Health Survey (NFHS)",
    "National Family Health Survey-5 ",
    "National Fisheries Development Board Annual Report",
    "National Judicial Data Grid",
    "National Sample Survey",
    "National Sample Survey ",
    "National Sample Survey (NSS)",
    "National Water Monitoring Program (NWMP) Water Quality Data",
    "Panchayati Raj Statistics",
    "Parliamentary Statistics",
    "Periodic Labour Force Survey",
    "Population Census 2001",
    "Population Census 2011",
    "Pradhan Mantri Adarsh Gram Yojana (PMAGY)",
    "Pradhan Mantri Awas Yojana (Urban) (PMAY)",
    "Pradhan Mantri Fasal Bima Yojana",
    "Pradhan Mantri Fasal Bima Yojana (PMFBY)",
    "Pradhan Mantri Gram Sadak Yojana (PMGSY)",
    "Pradhan Mantri Jan Dhan Yojaya (PMJDY)",
    "Pradhan Mantri Kisan Sampada Yojana (PMKSY)",
    "Pradhan Mantri Shram Yogi Maandhan (PMSYM)",
    "Pradhan Mantri Ujjwala Yojana (PMUY)",
    "Prison Statistics",
    "Public Enterprises Survey",
    "Rainfall Statistics",
    "Rashtriya Krishi Vikas Yojana (RKVY)",
    "RBI Quarterly Statistics on Deposits and Credit of Scheduled Commercial Banks",
    "RBI-Annual Report",
    "Registered Company Master - Ministry of Corporate Affairs (MCA)",
    "Report of Trend and Progress of Banking in India",
    "Report on trend and progress of banking in India",
    "Report on Trend and Progress of Housing in India",
    "Reproductive Child Healthcare report",
    "Reserve Bank of India (RBI) Data Base on Indian Economy",
    "Road Statistics",
    "Rural Health Statistics",
    "Scheduled tribe (ST) Statistical Profile",
    "Scholarship Schemes",
    "School Examination Statistics",
    "Skill Development Dashboard",
    "Socio Economic and Caste Census (SECC)",
    "State Finances: A Study of Budgets",
    "State level Power Peak Demand and Peak Met",
    "State Month Requirement Avail of chemical Fertilizers",
    "State Wise Deployment of ATMs",
    "Statistical Tables Relating to Banks",
    "Steel Capacity and Production",
    "Sub-mission on Agricultural Mechanization (SMAM)",
    "Sustainable Development Goals (SDG) India Index",
    "Telecom Subscription Data",
    "Textile Data",
    "Tourism Statistics",
    "UIDAI Data",
    "Unified District Information System for Education (UDISE)",
    "Update on Indian Port Sector",
    "Water Resources Information System (WRIS)",
  ],
};

export default basicData;
